from turtle import *
shape('turtle')
fillcolor('lightgray')
begin_fill()
circle(90)
end_fill()
fillcolor('lightblue')
begin_fill()
circle(50)
end_fill()
fillcolor('black')
begin_fill()
circle(20)
end_fill()
hideturtle()